wallpaper {
    monitor = DP-3
    path = ~/Pictures/wallpapers/vertical
    timeout = 300
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/Pictures/wallpapers/horizontal
    timeout = 300
    fit_mode = cover
}
